main: br.com.viniciusbautitz.shortner.Shortner
version: 1.0
load: POSTWORLD

name: Shortner
author: Bautitz
website: viniciusbautitz.com.br

commands:
  short:
    description: "Comando principal do plugin"

permissions:
  shortner.*:
    children:
      shortner.short.*: true
  shortnet.short.*:
    children:
      shortnet.short.use: true
      shortner.short.get: true
      shortner.short.remove: true
      shortner.short.create: true